[HomeTitle]
description = "Title of the home page."
other = "Home"

[LoginButtonForgotPassword]
description = "Forgot Password button in the login form."
other = "Forgot Password"

[LoginButtonLoginDiscord]
description = "Login with Discord button in the login form."
other = "Login with {{.Icon}} Discord"

[LoginButtonSignIn]
description = "Sign In button in the login form."
other = "Sign In"

[LoginHeader]
description = "Header of the login page."
other = "Please sign in"

[LoginLabelEmailAddress]
description = "Email address field label in the login form."
other = "Email address"

[LoginLabelPassword]
description = "Password field label in the login form."
other = "Password"

[LoginTitle]
description = "Title of the login page."
other = "Login"

[NavbarAdmin]
description = "Admin button on Navbar"
other = "Admin"

[NavbarAdminUsers]
description = "Users button on Navbar in the Admin Menu"
other = "Users"

[NavbarResponder]
description = "Responder button on Navbar"
other = "Responder"

[NavebarHome]
description = "Home button on Navbar"
other = "Home"

[PurgatoryHeader]
description = "Header of the purgatory page."
other = "Purgatory"

[PurgatoryText]
description = "Text of the purgatory page."
other = "If you're seeing this page you're not approved to use MegaBot. Please contact the administrator."

[PurgatoryTitle]
description = "Title of the purgatory page."
other = "Purgatory"
