[HomeTitle]
description = "Title of the home page."
other = "Home"

[NavbarAdmin]
description = "Admin button on Navbar"
other = "Admin"

[NavbarAdminUsers]
description = "Users button on Navbar in the Admin Menu"
other = "Users"

[NavbarResponder]
description = "Responder button on Navbar"
other = "Responder"

[NavebarHome]
description = "Home button on Navbar"
other = "Home"

[PurgatoryHeader]
description = "Header of the purgatory page."
other = "Purgatory"

[PurgatoryText]
description = "Text of the purgatory page."
other = "If you're seeing this page you're not approved to use MegaBot. Please contact the administrator."

[PurgatoryTitle]
description = "Title of the purgatory page."
other = "Purgatory"
