[NavbarAdmin]
description = "Admin button on Navbar"
other = "Admin"

[NavbarAdminUsers]
description = "Users button on Navbar in the Admin Menu"
other = "Users"

[NavbarResponder]
description = "Responder button on Navbar"
other = "Responder"

[NavebarHome]
description = "Home button on Navbar"
other = "Home"

[TitleHome]
description = "Title of the home page."
other = "Home"
