[Add]
description = "the word: add"
other = "add"

[AddResponder]
description = "the phrase: add responder"
one = "add responder"
other = "add responders"

[Admin]
description = "if possible, the abbreviated form of the word: administrator"
one = "admin"
other = "admins"

[EmailAddress]
description = "the phrase: email address"
one = "email address"
other = "email addresses"

[ForgotPassword]
description = "the phrase: forgot password"
other = "forgot password"

[Login]
description = "the word: login"
one = "login"
other = "logins"

[LoginDiscord]
description = "the capitalized phrase: Login with {{.Icon}} Discord"
other = "Login with {{.Icon}} Discord"

[Password]
description = "the word: password"
one = "password"
other = "passwords"

[Purgatory]
description = "the word: purgatory"
one = "purgatory"
other = "purgatories"

[PurgatoryPageText]
description = "Text of the purgatory page."
other = "If you're seeing this page you're not approved to use MegaBot. Please contact the administrator."

[Responder]
description = "the word: responder"
one = "responder"
other = "responders"

[SignIn]
description = "the phrase: sign in"
other = "sign in"

[SignInAsk]
description = "the sentence: Please sign in."
other = "Please sign in."

[User]
description = "the word: user"
one = "user"
other = "users"

[WebHome]
description = "in the context of the internet, the word: home"
other = "home"
